/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;
import com.mysql.jdbc.Statement;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Date;
import java.util.*;
import javax.swing.ImageIcon;
import static newpackage.bill.vamount;
//import java.lang.*;
/**
 *
 * @author KURUGONDA VENU
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    String futures;
    public HOME() {
        initComponents();
        groupbutton();
        Image img=new ImageIcon(this.getClass().getResource("./logo1.png")).getImage();
        this.setIconImage(img);
        
        
    }
    public void groupbutton()
    {
        buttonGroup1.add(yes);
         buttonGroup1.add(no);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcb1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        venu = new javax.swing.JLabel();
        jcb2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcb3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        briding1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        yes = new javax.swing.JCheckBox();
        no = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        ariding = new javax.swing.JTextField();
        sdate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalamount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        amount1v = new javax.swing.JTextField();
        amount2f = new javax.swing.JTextField();
        amount3g = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(154, 152, 129));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 239, 190));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book a Vichicle");

        jcb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Two_wheelers", "Three_wheelers", "Four_wheelers" }));
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("choose the Modal:");

        venu.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        venu.setForeground(new java.awt.Color(255, 255, 255));
        venu.setText("choose the  wheelers:");

        jcb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("choose the Brand:");

        jcb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Do you want any special features:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter how many days your trip");

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter the km (reading) after Riding:");

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter the km(reading) before Riding:");

        yes.setText("yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter the journey Starting date:");

        pay.setText("Proceed to Pay");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("dd/mm/yyyy");

        totalamount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("You have  to pay the amount:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/arrow (2).jpg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        amount1v.setBackground(new java.awt.Color(154, 152, 129));
        amount1v.setForeground(new java.awt.Color(154, 152, 129));
        amount1v.setBorder(null);

        amount2f.setBackground(new java.awt.Color(154, 152, 129));
        amount2f.setForeground(new java.awt.Color(154, 152, 129));
        amount2f.setBorder(null);

        amount3g.setBackground(new java.awt.Color(154, 152, 129));
        amount3g.setForeground(new java.awt.Color(154, 152, 129));
        amount3g.setBorder(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(537, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(venu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(briding1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ariding, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount1v, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(415, 415, 415))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(totalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(amount2f, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(amount3g, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(424, 424, 424)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(briding1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(venu)
                            .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ariding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yes)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount1v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount2f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount3g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(380, 380, 380))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(366, 366, 366))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb2ActionPerformed
        // TODO add your handling code here:
        try
        {
        if(jcb2.getSelectedItem().equals("Hero"))
        {
            //jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           
           jcb3.addItem("Hero Splendor Plus");
            jcb3.addItem("Hero HF Deluxe");
             jcb3.addItem("Hero Glamour");
             jcb3.addItem("Hero Xtreme 160R");
             jcb3.addItem("Hero Passion Pro");
             jcb3.addItem("Hero Xpulse 200 4V");
             jcb3.addItem("Hero Pleasure +");
             jcb3.addItem("Hero Xpulse 200T 4V");
             jcb3.addItem("Hero Destini 125 Xtec");
             
        }
        if(jcb2.getSelectedItem().equals("Honda"))
        {
            //jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem("Honda Shine");
            jcb3.addItem("Honda Unicorn");
             jcb3.addItem("Honda H'ness CB350");
             jcb3.addItem("Honda XBlade");
             jcb3.addItem("Honda Livo");
             jcb3.addItem("Honda cd 110 Dream");
             jcb3.addItem("Honda CBR650R");
             jcb3.addItem("Honda CB350RS");
             jcb3.addItem("Honda Activa 5G");
             jcb3.addItem("Honda Activa 4G");           
        }
        if(jcb2.getSelectedItem().equals("Yamaha"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
          // jcb3.setSelectedItem(null);
           jcb3.addItem("Yamaha MT 15 V2");
            jcb3.addItem("Yamaha FZ S FI");
             jcb3.addItem("Yamaha FZ FI");
             jcb3.addItem("Yamaha R15S");
             jcb3.addItem("Yamaha FZ25");
             jcb3.addItem("Yamaha FZ X");
             jcb3.addItem("Yamaha Ray ZR 125");
             jcb3.addItem("Yamaha Fascino 125");
             jcb3.addItem("Yamaha Aerox 155");
             jcb3.addItem("Yamaha R15 V4");           
        }
        if(jcb2.getSelectedItem().equals("KTM"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem("KTM 200 Duke");
            jcb3.addItem("KTM 390 Duke");
             jcb3.addItem("KTM 250 Duke");
             jcb3.addItem("KTM 125 Duke");
             jcb3.addItem("KTM RC 200");
             jcb3.addItem("KTM RC 390");
             jcb3.addItem("KTM RC 125");
             jcb3.addItem("KTM 390 Adventure");
             jcb3.addItem("KTM 250 Adventure");
             jcb3.addItem("KTM 390 Adventure X");           
        }
        if(jcb2.getSelectedItem().equals("Royal Enfield"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem("Royal Enfield Hunter 350");
            jcb3.addItem("Royal Enfield Classic 350");
             jcb3.addItem("Royal Enfield Bullet 350");
             jcb3.addItem("Royal Enfield Continental GT 650");
             jcb3.addItem("Royal Enfield Meteor 350");
             jcb3.addItem("Royal Enfield Himalayan");
             jcb3.addItem("Royal Enfield Super Meteor 650");
             jcb3.addItem("Royal Enfield Interceptor 650");
             jcb3.addItem("Royal Enfield Scram 411");
             //jcb3.addItem("Honda Activa 4G");           
        }
        if(jcb2.getSelectedItem().equals("Jawa"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem("Jawa 42");
            jcb3.addItem("Jawa 42 Bobber");
             jcb3.addItem("Jawa Perak");
             jcb3.addItem("Jawa Standard");
                      
        }
        if(jcb2.getSelectedItem().equals("TVS"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem("TVS Raider 125");
            jcb3.addItem("TVS Apache RTR 160");
             jcb3.addItem("TVS Ntorq 125");
             jcb3.addItem("TVS Sport");
             jcb3.addItem("TVS Jupiter");
             jcb3.addItem("TVS Jupiter 125");
             jcb3.addItem("TVS Star City Plus");
             jcb3.addItem("TVS Radeon");
             jcb3.addItem("TVS Scooty Pep Plus");
             jcb3.addItem("TVS XL 100 HEAVY DUTY");           
        }
        if(jcb2.getSelectedItem().equals("Auto"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem("Mahindra Alfa 3 Wheeler");
            jcb3.addItem("Bajaj Compact RE 3 Wheeler");
             jcb3.addItem("Kinetic Safar Smart 3 Wheeler");
             jcb3.addItem(" Bajaj Maxima C 3 Wheeler");
              jcb3.addItem("Piaggio Ape E City 3 Wheeler");
                   
        }
        if(jcb2.getSelectedItem().equals("E-Rikshaw"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem("Mahindra Treo");
            jcb3.addItem("Mahindra E-Alfa mini");
             jcb3.addItem("Mahindra Treo Yaari");
             jcb3.addItem(" Mini Metro E Rickshaw");
              jcb3.addItem("E-Ashwa E Rickshaw");
              jcb3.addItem("YC Electric Yatri Super");
              jcb3.addItem("JSA E Rickshaw");
                   
        }
        if(jcb2.getSelectedItem().equals("BMW"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem("BMW i");
            jcb3.addItem("BMW M340i");
             jcb3.addItem("BMW X1");
             jcb3.addItem(" BMW Z4");
              jcb3.addItem("BMW 2 ");
              
                   
        }
        if(jcb2.getSelectedItem().equals("Maruthi Suzuki"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem(" Fronx");
            jcb3.addItem(" Brezza");
             jcb3.addItem(" Swift");
             jcb3.addItem(" Grand Vitara");
              jcb3.addItem("Ertiga");
              
                   
        }
        if(jcb2.getSelectedItem().equals("TATA"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem(" Nexon");
            jcb3.addItem(" Punch");
             jcb3.addItem(" Tiago");
             jcb3.addItem(" Harrier");
              jcb3.addItem("Altroz");
              
                   
        }
        if(jcb2.getSelectedItem().equals("Ford"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem(" EcoSport");
            jcb3.addItem(" Endeavour");
             jcb3.addItem(" Figo");
             jcb3.addItem(" Aspire");
              jcb3.addItem("Fiesta");
              
                   
        }
        if(jcb2.getSelectedItem().equals("Hyundai"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem(" Creta");
            jcb3.addItem(" Venue");
             jcb3.addItem(" verna");
             jcb3.addItem(" Aura");
              jcb3.addItem("Tucson");
              
                   
        }
        if(jcb2.getSelectedItem().equals("Kia"))
        {
           // jcb3.setSelectedItem(null);
            jcb3.removeAllItems();
           //jcb3.setSelectedItem(null);
           jcb3.addItem(" Carens");
            jcb3.addItem(" Carnival");
             jcb3.addItem(" Sonet Facelift");
             jcb3.addItem(" Ev9");
              jcb3.addItem("Rio");
              
                   
        }
        if(jcb2.getSelectedItem().equals("Toyota"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Toyota is not availble in my store\n please select another modal");
             }
        if(jcb2.getSelectedItem().equals("Renault"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Renault is not availble in my store\n please select another modal");
             }
        
        
        }catch(Exception e)
        {
           System.out.println(e);
        }
    }//GEN-LAST:event_jcb2ActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
        try
        {
        if(jcb1.getSelectedItem().equals("Two_wheelers"))
        {
            jcb2.removeAllItems();
           //jcb2.setSelectedItem(null);
           jcb2.addItem("Hero");
            jcb2.addItem("Honda");
             jcb2.addItem("Yamaha");
             jcb2.addItem("KTM");
             jcb2.addItem("Royal Enfield");
             jcb2.addItem("TVS");
             jcb2.addItem("Jawa");
             
           
        }
        if(jcb1.getSelectedItem().equals("Three_wheelers"))
        {
            jcb2.removeAllItems();
          // jcb2.setSelectedItem(null);
           jcb2.addItem("Auto");
            jcb2.addItem("E-Rikshaw");
             
           
        }  
         if(jcb1.getSelectedItem().equals("Four_wheelers"))
        {
            jcb2.removeAllItems();
          // jcb2.setSelectedItem(null);
           jcb2.addItem("BMW");
           jcb2.addItem("Maruthi Suzuki");
           jcb2.addItem("TATA");
           jcb2.addItem("Ford");
           jcb2.addItem("Hyundai");
           jcb2.addItem("Kia");
           jcb2.addItem("Toyota");
           jcb2.addItem("Renault");
           
            
           
        }
         
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
              
        
    }//GEN-LAST:event_jcb1ActionPerformed

    private void jcb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb3ActionPerformed
        // TODO add your handling code here:
        try
        {
           
        if(jcb3.getSelectedItem().equals("Honda Unicorn"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Honda Unicarn is not availble in my store\n please select another modal");
             }
        if(jcb3.getSelectedItem().equals("TVS Raider 125"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"TVS Raider 125 is not availble in my store\n please select another modal");
             }
        if(jcb3.getSelectedItem().equals("Jawa 42 Bobber"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Jawa 42 Bobber is not availble in my store\n please select another modal");
             }
        if(jcb3.getSelectedItem().equals("KTM 390 Adventure"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"KTM 390 Adventure is not availble in my store\n please select another modal");
             }
        if(jcb3.getSelectedItem().equals("Royal Enfield Continental GT 650"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Royal Enfield Continental GT 650 is not availble in my store\n please select another modal");
             }
        if(jcb3.getSelectedItem().equals("Yamaha Fascino 125"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Yamaha Fascino 125 is not availble in my store\n please select another modal");
             }
         if(jcb3.getSelectedItem().equals("Figo"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Yamaha Fascino 125 is not availble in my store\n please select another modal");
             }
         if(jcb3.getSelectedItem().equals("BMW M340i"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Yamaha Fascino 125 is not availble in my store\n please select another modal");
             }
         if(jcb3.getSelectedItem().equals("Harrier"))
             {
                 javax.swing.JOptionPane.showMessageDialog(this,"Yamaha Fascino 125 is not availble in my store\n please select another modal");
             }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jcb3ActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        String wheele = jcb1.getSelectedItem().toString();
        String brand = jcb2.getSelectedItem().toString();
        String modal = jcb3.getSelectedItem().toString();
        String riding1 = briding1.getText().toString();
        String riding2 = ariding.getText().toString();
        String date1 = sdate.getText().toString();
        String date2 = edate.getText().toString();
        String amount1=amount1v.getText().toString();
        String amount2=amount2f.getText().toString();
        String amount3=amount3g.getText().toString();
        String amount=totalamount.getText().toString();
      
        
        if(wheele.isEmpty()||brand.isEmpty()||modal.isEmpty()||riding1.isEmpty()||riding2.isEmpty()||date1.isEmpty()||date2.isEmpty())
        {
             javax.swing.JOptionPane.showMessageDialog(this,"All fields are required");
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Do you want to pay Amount");
           
        Payment p1=new Payment();
        p1.setVisible(true);
        this.setVisible(false);
           
        }
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String databaseURL="jdbc:mysql://localhost:3306/database";
            Connection con=DriverManager.getConnection(databaseURL,"root","");
            Statement stat = (Statement) con.createStatement();
            String insertQuery="insert into home values('"+wheele+"', '"+brand+"', '"+modal+"', '"+riding1+"','"+riding2+"','"+date1+"','"+date2+"','"+futures+"','"+amount1+"','"+amount2+"','"+amount3+"','"+amount+"' )";
            
            int x=stat.executeUpdate(insertQuery);
            System.out.println(x);
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
        
    }//GEN-LAST:event_payActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
          futures=yes.getText();
           try
        {
        //futures=no.getText();
           float a,b,c,d,e,t,g;
        a=Float.parseFloat(briding1.getText());
        b=Float.parseFloat(ariding.getText());
        d=Integer.parseInt(edate.getText());
        c=((b-a)*5);
        g=(c*6)/100;
        e=d*5;
        t=c+e+g;
        totalamount.setText("\u20B9 "+t);
       amount1v.setText("\u20B9"+c);
       amount2f.setText("\u20B9"+e);
       amount3g.setText("\u20B9"+g);
       
        }
        catch(Exception e)
                {
                    System.out.println(e);
                }
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
        
           futures=no.getText();
           try
        {
        //futures=no.getText();
        
           float a,b,c,g,t,e;
        a=Float.parseFloat(briding1.getText());
        b=Float.parseFloat(ariding.getText());
        c=(b-a)*3;
        g=(c*6)/100;
        e=0;
        t=c+g+e;
        totalamount.setText("\u20B9 "+c);
        amount1v.setText("\u20B9 "+c);
       amount2f.setText("\u20B9"+e);
       amount3g.setText("\u20B9"+g);
       
        
        }
        catch(Exception e)
                {
                    System.out.println(e);
                }
    }//GEN-LAST:event_noActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        NewJFrame n= new NewJFrame();
       n.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField amount1v;
    public static javax.swing.JTextField amount2f;
    public static javax.swing.JTextField amount3g;
    public static javax.swing.JTextField ariding;
    public static javax.swing.JTextField briding1;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField edate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcb1;
    private javax.swing.JComboBox<String> jcb2;
    private javax.swing.JComboBox<String> jcb3;
    public static javax.swing.JCheckBox no;
    public javax.swing.JButton pay;
    private javax.swing.JTextField sdate;
    public static javax.swing.JTextField totalamount;
    private javax.swing.JLabel venu;
    public static javax.swing.JCheckBox yes;
    // End of variables declaration//GEN-END:variables
}
